version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db_tasks
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tasks
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/tasks
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
