apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend-production
  labels:
    app: nest-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      containers:
        - name: backend
          image: ${{ secrets.DOCKER_USERNAME }}/app-production:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nest-backend-production
spec:
  selector:
    app: nest-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
