name: Deploy Aplicação - Staging

on:
  push:
    branches:
      - main
    paths:
      - "app/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Docker
        uses: docker/setup-buildx-action@v2

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_STAGING }}

      - name: Build e Push da imagem para o GCR
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID_STAGING }}/app-staging:latest
          docker build -t $IMAGE_NAME ./app
          docker push $IMAGE_NAME

      - name: Setar contexto do cluster
        run: |
          gcloud container clusters get-credentials gke-staging --region us-central1 --project ${{ secrets.GCP_PROJECT_ID_STAGING }}

      - name: Aplicar Manifests
        run: kubectl apply -f k8s/deployment-staging.yml