name: Deploy Aplicação - Production

on:
  push:
    paths:
      - "app/**"
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Docker
        uses: docker/setup-buildx-action@v2

      - name: Login no DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push da imagem
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app-production:latest ./app
          docker push ${{ secrets.DOCKER_USERNAME }}/app-production:latest

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_PRODUCTION }}

      - name: Setar contexto do cluster
        run: |
          gcloud container clusters get-credentials gke-production --region us-central1 --project ${{ secrets.GCP_PROJECT_ID_PRODUCTION }}

      - name: Aplicar Manifests
        run: kubectl apply -f k8s/deployment-production.yml