name: Deploy Aplicação - Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Instalar gke-gcloud-auth-plugin via gcloud
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_PRODUCTION }}

      - name: Autenticar Docker com GCR
        run: gcloud auth configure-docker --quiet

      - name: Build e Push da imagem para o GCR
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID_PRODUCTION }}/app-production:latest
          docker build -t $IMAGE_NAME ./back
          docker push $IMAGE_NAME

      - name: Setar contexto do cluster
        run: |
          gcloud container clusters get-credentials gke-production --region us-central1 --project ${{ secrets.GCP_PROJECT_ID_PRODUCTION }}

      - name: Aplicar Manifests
        run: kubectl apply -f k8s/deployment-production.yml
